# Generated by Django 4.2.30 on 2026-07-10 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Averia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('averia', models.CharField(help_text='Descripción de la avería', max_length=100)),
                ('sintoma', models.CharField(help_text='Síntomas de la avería', max_length=100)),
                ('solucion', models.CharField(help_text='Solución a la avería', max_length=100)),
                ('ref', models.CharField(blank=True, help_text='Referencias asociadas a la avería, separadas por comas', max_length=150)),
                ('ult_edic', models.CharField(help_text='Usuario de la última edición', max_length=15)),
                ('ult_fecha', models.DateField(auto_now=True, help_text='Fecha de la última edición')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.mastermodelos')),
            ],
        ),
    ]
