# Generated by Django 6.0.7 on 2026-07-10 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterequipos',
            name='tipo',
            field=models.CharField(help_text='Tipo de equipo', max_length=50),
        ),
        migrations.AlterField(
            model_name='mastermodelos',
            name='modelo',
            field=models.CharField(help_text='Modelo de equipo', max_length=50, unique=True),
        ),
    ]
